In [6]:
%pylab inline --no-import-all

from __future__ import division, print_function
import pandas as pd

pd.options.display.max_columns = 50

Populating the interactive namespace from numpy and matplotlib

Load the data corresponding to the most recent date

In [8]:
# Data is assumed to be in directory data/
with open('data/colnames.py', 'r') as myfile:
    columns_names_dict = eval(myfile.read())
data = pd.read_csv("data/MaxDate_train.csv", parse_dates=[0,6,10], dtype={"cod_prov":str, "conyuemp":str},
                         skipinitialspace=True)
data.rename(columns=columns_names_dict, inplace=True)

data.describe()

,CUST_ID,CUST_AGE,NEW_CUST,SENIORITY_MNTH,PRMRY_CUST,RESID_TYPE,CUST_ACTIVE,CUST_HOUSINCOM,IND_SAVINGS,IND_GARNTEES,IND_CURNTACCNT,IND_DERIVADA,IND_PAYRLACCNT,IND_JUNIOR,IND_MASPART,IND_PARTIC,IND_PARTPLUS,IND_STDEPACCNT,IND_MTDEPACCNT,IND_LTDEPACCNT,IND_EACCNT,IND_FUNDS,IND_MORTGAGE,IND_PENSNPLAN,IND_LOANS,IND_TAXES,IND_CREDCARD,IND_SECURIT,IND_HOMEACCNT,IND_PAYROLL,IND_PENSIONS,IND_DIRECTDEBT
count,9.314530e+05,931453.000000,931453.000000,931453.000000,931453.000000,931453.0,931453.000000,7.024350e+05,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000,931453.000000
mean,8.799972e+05,40.168298,0.036890,76.670527,1.196746,1.0,0.424845,1.340896e+05,0.000084,0.000017,0.602945,0.000339,0.078438,0.008139,0.008693,0.107991,0.035719,0.000340,0.001096,0.033514,0.081427,0.015768,0.004861,0.007901,0.002138,0.048886,0.037385,0.023003,0.003177,0.051864,0.056737,0.121370
std,4.483382e+05,17.185403,0.188491,1796.050924,4.386622,0.0,0.494320,2.322205e+05,0.009151,0.004145,0.489288,0.018416,0.268859,0.089848,0.092829,0.310370,0.185590,0.018445,0.033090,0.179975,0.273489,0.124576,0.069553,0.088533,0.046184,0.215630,0.189702,0.149912,0.056273,0.221753,0.231340,0.326556
min,1.588900e+04,2.000000,0.000000,-999999.000000,1.000000,1.0,0.000000,1.202730e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.837490e+05,25.000000,0.000000,22.000000,1.000000,1.0,0.000000,6.849379e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,9.668510e+05,38.000000,0.000000,54.000000,1.000000,1.0,0.000000,1.014934e+05,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.265166e+06,50.000000,0.000000,134.000000,1.000000,1.0,1.000000,1.555464e+05,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.553689e+06,164.000000,1.000000,256.000000,99.000000,1.0,1.000000,2.889440e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Let's define a distance between profiles

In [7]:
data.head()

,FETCH_DATE,CUST_ID,EMPLYMT_STATUS,RESID_CNTRY,CUST_SEX,CUST_AGE,FIRSTHOLD_DATE,NEW_CUST,SENIORITY_MNTH,PRMRY_CUST,PRMRY_LASTDATE,CUST_TYPE,CUST_ACTIVITY,RESID_IDX,FOREIGN_IDX,SPOUSE_EMPLOY,JOIN_CHANNEL,DECEASED,RESID_TYPE,RESID_ADDR_CD,RESID_ADDR_NM,CUST_ACTIVE,CUST_HOUSINCOM,CUSTIND_SEGMNT,IND_SAVINGS,IND_GARNTEES,IND_CURNTACCNT,IND_DERIVADA,IND_PAYRLACCNT,IND_JUNIOR,IND_MASPART,IND_PARTIC,IND_PARTPLUS,IND_STDEPACCNT,IND_MTDEPACCNT,IND_LTDEPACCNT,IND_EACCNT,IND_FUNDS,IND_MORTGAGE,IND_PENSNPLAN,IND_LOANS,IND_TAXES,IND_CREDCARD,IND_SECURIT,IND_HOMEACCNT,IND_PAYROLL,IND_PENSIONS,IND_DIRECTDEBT
0,2016-05-28,657640,N,ES,H,68,2006-11-17,0,114,1,NaT,1,I,S,N,NaN,KAQ,N,1,28,MADRID,0,147347.97,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2016-05-28,657788,N,ES,H,42,2006-11-18,0,114,1,NaT,1,A,S,N,NaN,KBF,N,1,28,MADRID,1,132559.35,02 - PARTICULARES,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2016-05-28,657795,N,ES,V,44,2006-11-18,0,114,1,NaT,1,A,S,N,NaN,KAP,N,1,26,"RIOJA, LA",1,81399.57,02 - PARTICULARES,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2016-05-28,657790,N,ES,V,42,2006-11-18,0,114,1,NaT,1,A,S,N,NaN,KBF,N,1,48,BIZKAIA,1,NaN,02 - PARTICULARES,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1
4,2016-05-28,657794,N,ES,H,49,2006-11-18,0,114,1,NaT,1,A,S,N,NaN,KAT,N,1,8,BARCELONA,1,102189.00,01 - TOP,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
col_types = {"EMPLYMT_STATUS" : "cat", "RESID_CNTRY" : "cat", "CUST_SEX" : "cat", "CUST_AGE" : "cont", "FIRSTHOLD_DATE" : "cont", "NEW_CUST" : "cat", "SENIORITY_MNTH" : "cont", "PRMRY_CUST" : "cat", "PRMRY_LASTDATE" : "cont",  "CUST_TYPE" : "cat", "CUST_ACTIVITY" : "cat", "RESID_IDX" : "cat", "FOREIGN_IDX" : "cat", "SPOUSE_EMPLOY" : "cat", "JOIN_CHANNEL" : "cat", "DECEASED" : "cat", "RESID_TYPE" : "cat", "RESID_ADDR_CD" : "cat", "RESID_ADDR_NM": "cat", "CUST_ACTIVE" : "cat", "CUST_HOUSINCOM" : "cont", "CUSTIND_SEGMNT" : "cat"}